<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-07-21T19:19:31 IST" name="Default suite" finished-at="2025-07-21T19:19:45 IST" duration-ms="13994">
    <groups>
    </groups>
    <test started-at="2025-07-21T19:19:31 IST" name="Default test" finished-at="2025-07-21T19:19:45 IST" duration-ms="13994">
      <class name="com.ect.testCases.LoginTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.ect.testCases.LoginTest@71cf1b07]" started-at="2025-07-21T19:19:31 IST" name="setup" finished-at="2025-07-21T19:19:37 IST" duration-ms="6136" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="Logintest(java.lang.String,java.lang.String)[pri:0, instance:com.ect.testCases.LoginTest@71cf1b07]" started-at="2025-07-21T19:19:38 IST" name="Logintest" data-provider="loginData" finished-at="2025-07-21T19:19:42 IST" duration-ms="4035" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[amanmouryan30+99@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Qwerty@123]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Logintest -->
        <test-method signature="Logintest(java.lang.String,java.lang.String)[pri:0, instance:com.ect.testCases.LoginTest@71cf1b07]" started-at="2025-07-21T19:19:42 IST" name="Logintest" data-provider="loginData" finished-at="2025-07-21T19:19:43 IST" duration-ms="955" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[amaninvalidmail@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Password123]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at com.ect.testCases.LoginTest.Logintest(LoginTest.java:18)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Logintest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.ect.testCases.LoginTest@71cf1b07]" started-at="2025-07-21T19:19:43 IST" name="tearDown" finished-at="2025-07-21T19:19:45 IST" duration-ms="1888" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.ect.testCases.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
